project_id = "cnoqjiucrecktwsbhqts"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.kiwify-webhook]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.send-team-invite]
    verify_jwt = true
